name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black mypy coverage

      # 1️⃣ Linting with flake8
      - name: Run flake8
        run: |
          flake8 . --max-line-length=88 --ignore=E203,W503

      # 2️⃣ Formatting check with black
      - name: Run Black (check only)
        run: |
          black --check .

      # 3️⃣ Type-checking with mypy
      - name: Run mypy
        run: |
          mypy .

      # 4️⃣ Run unit tests with coverage
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=.

      # 5️⃣ Upload coverage to GitHub summary
      - name: Upload coverage
        run: |
          coverage xml
