name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black bandit pytest

      - name: Lint with flake8
        run: |
          echo "Running flake8 for linting..."
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Check formatting with black
        run: |
          echo "Checking code formatting..."
          black --check .

      - name: Security scan with bandit
        run: |
          echo "Running Bandit security checks..."
          bandit -r .

      - name: Run unit tests with pytest
        run: |
          echo "Running tests..."
          pytest --maxfail=3 --disable-warnings -q
